//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaDetalle
    {
        public int Id { get; set; }
        public int EntradaId { get; set; }
        public int ProductoId { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public int Cantidad { get; set; }
        public string Lote { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual Entrada Entrada { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
